version: "3.9"

services:
  express-demo:
    build: services/express-demo
    ports:
      - "3000:3000"
  registry:
    build: services/registry
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
